# Potato CET Pipeline
## Notebook 01: Data Import and Quality Control

**Project:** Multi-environment Potato CET Trials (2025)

**Locations**
- Molo
- Njoro
- Nairobi (UON)

**Populations**
- EA21
- LBHT

Author: Mary Adungosi

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
from pathlib import Path

PROJECT = Path("/content/drive/MyDrive/Potato_CET_Project")
print(PROJECT.exists())

True

In [3]:
import pandas as pd
import numpy as np

from pathlib import Path
import os

In [4]:
import os

print(os.listdir("/content/drive/MyDrive/Potato_CET_Project"))

['notebooks', 'data_raw', 'data_clean', 'figures', 'outputs', 'metadata', 'scripts', 'data']

In [8]:
print(os.listdir("/content/drive/MyDrive/Potato_CET_Project/data_raw"))

['KE25NJO-EA21-AT01_table-Final.xlsx', 'KE25MOL-EA21-AT01_table-Final.xlsx', 'KE25MOL-LBHT-IT01_table-Final.xlsx', 'KE25NJO-LBHT-IT01_table-Final.xlsx', 'KE25UON-EA21-AT01_table-Final.xlsx', 'KE25UON-LBHT-IT01_table-Final.xlsx']

In [9]:
print(RAW)
print(RAW.exists())

/content/drive/MyDrive/Potato_CET_Project/data_raw
True

In [10]:
from pathlib import Path

RAW = Path("/content/drive/MyDrive/Potato_CET_Project/data_raw")

files = list(RAW.glob("*.xlsx"))

print(files)

[PosixPath('/content/drive/MyDrive/Potato_CET_Project/data_raw/KE25NJO-EA21-AT01_table-Final.xlsx'), PosixPath('/content/drive/MyDrive/Potato_CET_Project/data_raw/KE25MOL-EA21-AT01_table-Final.xlsx'), PosixPath('/content/drive/MyDrive/Potato_CET_Project/data_raw/KE25MOL-LBHT-IT01_table-Final.xlsx'), PosixPath('/content/drive/MyDrive/Potato_CET_Project/data_raw/KE25NJO-LBHT-IT01_table-Final.xlsx'), PosixPath('/content/drive/MyDrive/Potato_CET_Project/data_raw/KE25UON-EA21-AT01_table-Final.xlsx'), PosixPath('/content/drive/MyDrive/Potato_CET_Project/data_raw/KE25UON-LBHT-IT01_table-Final.xlsx')]

## Defining project paths/folders

In [11]:
PROJECT = Path("/content/drive/MyDrive/Potato_CET_Project")

RAW = PROJECT / "data_raw"
CLEAN = PROJECT / "data_clean"
OUTPUT = PROJECT / "outputs"
FIGURES = PROJECT / "figures"

## Listing available files

In [12]:
files = sorted(RAW.glob("*.xlsx"))

print(f"{len(files)} Excel files found\n")

for f in files:
    print(f.name)

6 Excel files found

KE25MOL-EA21-AT01_table-Final.xlsx
KE25MOL-LBHT-IT01_table-Final.xlsx
KE25NJO-EA21-AT01_table-Final.xlsx
KE25NJO-LBHT-IT01_table-Final.xlsx
KE25UON-EA21-AT01_table-Final.xlsx
KE25UON-LBHT-IT01_table-Final.xlsx

## Create the trial information table

In [13]:
trial_info = pd.DataFrame({

    "trial":[
        "KE25MOL-EA21",
        "KE25MOL-LBHT",
        "KE25NJO-EA21",
        "KE25NJO-LBHT",
        "KE25UON-EA21",
        "KE25UON-LBHT"
    ],

    "location":[
        "Molo",
        "Molo",
        "Njoro",
        "Njoro",
        "Nairobi",
        "Nairobi"
    ],

    "population":[
        "EA21",
        "LBHT",
        "EA21",
        "LBHT",
        "EA21",
        "LBHT"
    ]

})

trial_info

          trial location population
0  KE25MOL-EA21     Molo       EA21
1  KE25MOL-LBHT     Molo       LBHT
2  KE25NJO-EA21    Njoro       EA21
3  KE25NJO-LBHT    Njoro       LBHT
4  KE25UON-EA21  Nairobi       EA21
5  KE25UON-LBHT  Nairobi       LBHT

## Reading every Excel file automatically

In [14]:
trial_data = {}

for file in files:

    trial = Path(file).stem
    trial_data[trial] = {}

    print(f"\nProcessing: {trial}")

    xls = pd.ExcelFile(file)

    for sheet in xls.sheet_names:

        df = pd.read_excel(file, sheet_name=sheet)

        # Skip empty sheets
        if df.empty or df.dropna(how="all").empty:
            print(f"   Skipping empty sheet: {sheet}")
            continue

        if df.shape[1] >= 70:
            trial_data[trial]["yield"] = df
            print(f"   Yield      -> {sheet} ({df.shape[0]} × {df.shape[1]})")
        else:
            trial_data[trial]["phenotype"] = df
            print(f"   Phenotype -> {sheet} ({df.shape[0]} × {df.shape[1]})")

Processing: KE25MOL-EA21-AT01_table-Final
   Phenotype -> 2025-09-26-09-05-49_KE25MOL-EA2 (174 × 44)
   Yield      -> EA21 MOLO-YIELD (174 × 80)

Processing: KE25MOL-LBHT-IT01_table-Final
   Phenotype -> 2025-09-26-09-06-28_KE25MOL-LBH (264 × 36)
   Yield      -> LBHT MOLO-Yield (264 × 80)

Processing: KE25NJO-EA21-AT01_table-Final
   Phenotype -> 2025-09-26-09-09-54_KE25NJO-EA2 (174 × 47)

Processing: KE25NJO-LBHT-IT01_table-Final
   Phenotype -> 2025-09-26-09-08-45_KE25NJO-LBH (264 × 44)
   Yield      -> LBHT NJORO-Yield (264 × 80)

Processing: KE25UON-EA21-AT01_table-Final
   Phenotype -> 2025-09-29-09-29-48_KE25UON-EA2 (180 × 45)
   Yield      -> EA21-UON_Yield (180 × 80)

Processing: KE25UON-LBHT-IT01_table-Final
   Phenotype -> 2025-09-29-09-25-47_KE25UON-LBH (264 × 45)
   Yield      -> LBHT UON_Yield  (264 × 80)

In [15]:
datasets = trial_data

In [16]:
for trial in datasets:
    print("\n", trial)
    for name, df in datasets[trial].items():
        print(f"{name:10s} {df.shape}")

 KE25MOL-EA21-AT01_table-Final
phenotype  (174, 44)
yield      (174, 80)

 KE25MOL-LBHT-IT01_table-Final
phenotype  (264, 36)
yield      (264, 80)

 KE25NJO-EA21-AT01_table-Final
phenotype  (174, 47)

 KE25NJO-LBHT-IT01_table-Final
phenotype  (264, 44)
yield      (264, 80)

 KE25UON-EA21-AT01_table-Final
phenotype  (180, 45)
yield      (180, 80)

 KE25UON-LBHT-IT01_table-Final
phenotype  (264, 45)
yield      (264, 80)

## Check what was imported

In [17]:
for trial in datasets:

    print(trial)

    print(datasets[trial].keys())
    print()

KE25MOL-EA21-AT01_table-Final
dict_keys(['phenotype', 'yield'])

KE25MOL-LBHT-IT01_table-Final
dict_keys(['phenotype', 'yield'])

KE25NJO-EA21-AT01_table-Final
dict_keys(['phenotype'])

KE25NJO-LBHT-IT01_table-Final
dict_keys(['phenotype', 'yield'])

KE25UON-EA21-AT01_table-Final
dict_keys(['phenotype', 'yield'])

KE25UON-LBHT-IT01_table-Final
dict_keys(['phenotype', 'yield'])

## Basic QC summary

In [18]:
summary = []

for trial in datasets:

    for sheet in datasets[trial]:

        df = datasets[trial][sheet]

        summary.append({

            "Trial":trial,
            "Sheet":sheet,
            "Rows":df.shape[0],
            "Columns":df.shape[1],
            "Missing cells":df.isna().sum().sum(),
            "Duplicate rows":df.duplicated().sum()

        })

summary = pd.DataFrame(summary)

summary

,Trial,Sheet,Rows,Columns,Missing cells,Duplicate rows
0,KE25MOL-EA21-AT01_table-Final,phenotype,174,44,3065,0
1,KE25MOL-EA21-AT01_table-Final,yield,174,80,1015,0
2,KE25MOL-LBHT-IT01_table-Final,phenotype,264,36,3228,0
3,KE25MOL-LBHT-IT01_table-Final,yield,264,80,1784,0
4,KE25NJO-EA21-AT01_table-Final,phenotype,174,47,3153,0
5,KE25NJO-LBHT-IT01_table-Final,phenotype,264,44,5600,0
6,KE25NJO-LBHT-IT01_table-Final,yield,264,80,1129,0
7,KE25UON-EA21-AT01_table-Final,phenotype,180,45,3070,0
8,KE25UON-EA21-AT01_table-Final,yield,180,80,1029,0
9,KE25UON-LBHT-IT01_table-Final,phenotype,264,45,4768,0
10,KE25UON-LBHT-IT01_table-Final,yield,264,80,1251,0

## checking column-wise missingness

In [19]:
from pathlib import Path
import pandas as pd

results = []

for file in sorted(RAW.glob("*.xlsx")):

    excel = pd.ExcelFile(file)

    for sheet in excel.sheet_names:

        # Ignore completely empty Sheet1
        if sheet.lower() == "sheet1":
            continue

        df = pd.read_excel(file, sheet_name=sheet)

        miss = (
            df.isna()
            .mean()
            .sort_values(ascending=False)
            *100
        )

        tmp = pd.DataFrame({
            "Variable": miss.index,
            "Percent_missing": miss.values,
            "Trial": file.stem,
            "Sheet": sheet
        })

        results.append(tmp)

missing_report = pd.concat(results, ignore_index=True)

missing_report.head()

,Variable,Percent_missing,Trial,Sheet
0,Late Blight 80 Days,100.0,KE25MOL-EA21-AT01_table-Final,2025-09-26-09-05-49_KE25MOL-EA2
1,Late Blight At 120 Days,100.0,KE25MOL-EA21-AT01_table-Final,2025-09-26-09-05-49_KE25MOL-EA2
2,Rotten Tubers,100.0,KE25MOL-EA21-AT01_table-Final,2025-09-26-09-05-49_KE25MOL-EA2
3,Photo,100.0,KE25MOL-EA21-AT01_table-Final,2025-09-26-09-05-49_KE25MOL-EA2
4,Selected and non Selected,100.0,KE25MOL-EA21-AT01_table-Final,2025-09-26-09-05-49_KE25MOL-EA2

want to see which variables are completely empty

In [20]:
missing_report[
    missing_report.Percent_missing==100
].sort_values(["Trial","Sheet"])

,Variable,Percent_missing,Trial,Sheet
0,Late Blight 80 Days,100.0,KE25MOL-EA21-AT01_table-Final,2025-09-26-09-05-49_KE25MOL-EA2
1,Late Blight At 120 Days,100.0,KE25MOL-EA21-AT01_table-Final,2025-09-26-09-05-49_KE25MOL-EA2
2,Rotten Tubers,100.0,KE25MOL-EA21-AT01_table-Final,2025-09-26-09-05-49_KE25MOL-EA2
3,Photo,100.0,KE25MOL-EA21-AT01_table-Final,2025-09-26-09-05-49_KE25MOL-EA2
4,Selected and non Selected,100.0,KE25MOL-EA21-AT01_table-Final,2025-09-26-09-05-49_KE25MOL-EA2
...,...,...,...,...
548,MTWCI,100.0,KE25UON-LBHT-IT01_table-Final,2025-09-29-09-25-47_KE25UON-LBH
549,Late Blight 40 Days,100.0,KE25UON-LBHT-IT01_table-Final,2025-09-29-09-25-47_KE25UON-LBH
550,Late Blight 60 Days,100.0,KE25UON-LBHT-IT01_table-Final,2025-09-29-09-25-47_KE25UON-LBH
581,Min. average NIR,100.0,KE25UON-LBHT-IT01_table-Final,LBHT UON_Yield
582,Max. average NIR,100.0,KE25UON-LBHT-IT01_table-Final,LBHT UON_Yield

### Variables with more than 95% missing

In [21]:
missing_report[
    missing_report.Percent_missing>=95
].sort_values(
    ["Trial","Percent_missing"],
    ascending=[True,False]
)

,Variable,Percent_missing,Trial,Sheet
0,Late Blight 80 Days,100.000000,KE25MOL-EA21-AT01_table-Final,2025-09-26-09-05-49_KE25MOL-EA2
1,Late Blight At 120 Days,100.000000,KE25MOL-EA21-AT01_table-Final,2025-09-26-09-05-49_KE25MOL-EA2
2,Rotten Tubers,100.000000,KE25MOL-EA21-AT01_table-Final,2025-09-26-09-05-49_KE25MOL-EA2
3,Photo,100.000000,KE25MOL-EA21-AT01_table-Final,2025-09-26-09-05-49_KE25MOL-EA2
4,Selected and non Selected,100.000000,KE25MOL-EA21-AT01_table-Final,2025-09-26-09-05-49_KE25MOL-EA2
...,...,...,...,...
550,Late Blight 60 Days,100.000000,KE25UON-LBHT-IT01_table-Final,2025-09-29-09-25-47_KE25UON-LBH
581,Min. average NIR,100.000000,KE25UON-LBHT-IT01_table-Final,LBHT UON_Yield
582,Max. average NIR,100.000000,KE25UON-LBHT-IT01_table-Final,LBHT UON_Yield
551,SELECTED CLONES,99.621212,KE25UON-LBHT-IT01_table-Final,2025-09-29-09-25-47_KE25UON-LBH
583,Average length (mm) 0-10,98.863636,KE25UON-LBHT-IT01_table-Final,LBHT UON_Yield

In [22]:
OUTPUT.mkdir(exist_ok=True)

missing_report.to_csv(
    OUTPUT/"column_missingness.csv",
    index=False
)

print("Saved.")

Saved.

### searching for variables that are completely empty

In [23]:
#==========================================================
# CELL 10
# Variables that are completely empty
#==========================================================

empty_columns = []

for trial_name, sheets_dict in datasets.items():

    for sheet_name, df in sheets_dict.items():

        if df.empty:
            continue

        pct_missing = df.isna().mean() * 100

        for col, pct in pct_missing.items():

            if pct == 100:

                empty_columns.append({
                    "Trial": trial_name,
                    "Sheet": sheet_name,
                    "Variable": col
                })

empty_df = pd.DataFrame(empty_columns)

print(f"Total completely empty variables: {len(empty_df)}")

display(empty_df.sort_values(["Trial","Sheet"]))

Total completely empty variables: 99

                            Trial      Sheet          Variable
0   KE25MOL-EA21-AT01_table-Final  phenotype               NPH
1   KE25MOL-EA21-AT01_table-Final  phenotype            NMTCII
2   KE25MOL-EA21-AT01_table-Final  phenotype            NNOMTP
3   KE25MOL-EA21-AT01_table-Final  phenotype             MTWCI
4   KE25MOL-EA21-AT01_table-Final  phenotype            MTWCII
..                            ...        ...               ...
94  KE25UON-LBHT-IT01_table-Final  phenotype       SE@110 DAYS
95  KE25UON-LBHT-IT01_table-Final  phenotype       SE@120 DAYS
96  KE25UON-LBHT-IT01_table-Final  phenotype      Tubers Shape
97  KE25UON-LBHT-IT01_table-Final      yield  Min. average NIR
98  KE25UON-LBHT-IT01_table-Final      yield  Max. average NIR

[99 rows x 3 columns]

Variables that are almost empty

In [24]:
#==========================================================
# CELL 11
# Variables with >95% missing
#==========================================================

almost_empty = []

for trial_name, sheets_dict in datasets.items():

    for sheet_name, df in sheets_dict.items():

        if df.empty:
            continue

        pct_missing = df.isna().mean()*100

        for col, pct in pct_missing.items():

            if 95 <= pct < 100:

                almost_empty.append({
                    "Trial": trial_name,
                    "Sheet": sheet_name,
                    "Variable": col,
                    "Percent Missing": round(pct,2)
                })

almost_empty_df = pd.DataFrame(almost_empty)

display(almost_empty_df.sort_values("Percent Missing",
                                    ascending=False))

,Trial,Sheet,Variable,Percent Missing
4,KE25UON-LBHT-IT01_table-Final,phenotype,SELECTED CLONES,99.62
3,KE25UON-EA21-AT01_table-Final,yield,Average length (mm) 0-10,99.44
5,KE25UON-LBHT-IT01_table-Final,yield,Average length (mm) 0-10,98.86
0,KE25MOL-LBHT-IT01_table-Final,yield,Average length (mm) 0-10,98.86
2,KE25UON-EA21-AT01_table-Final,phenotype,Late Blight 70 Days,97.78
1,KE25NJO-LBHT-IT01_table-Final,phenotype,Wilted,97.35

I want to know:

Which variables are common across all six trials, and which variables are unique to particular locations?

This will tell us:

- the core variables that every environment has,
- variables specific to Njoro,
- variables specific to Nairobi,
- variables specific to EA21 or LBHT.

That information is important before harmonizing the datasets.

### Creating a variable inventory

In [25]:
#==========================================================
# CELL 12
# Variable inventory across all trials
#==========================================================

variable_inventory = []

for trial_name, sheets_dict in datasets.items():

    for sheet_name, df in sheets_dict.items():

        if df.empty:
            continue

        for col in df.columns:

            variable_inventory.append({
                "Trial": trial_name,
                "Sheet": sheet_name,
                "Variable": col
            })

inventory = pd.DataFrame(variable_inventory)

summary = (
    inventory.groupby("Variable")
             .agg(
                 n_occurrences=("Variable", "count"),
                 trials=("Trial",
                         lambda x: ", ".join(sorted(set(x))))
             )
             .sort_values("n_occurrences",
                          ascending=False)
             .reset_index()
)

display(summary)

,Variable,n_occurrences,trials
0,row,11,"KE25MOL-EA21-AT01_table-Final, KE25MOL-LBHT-IT..."
1,rep,11,"KE25MOL-EA21-AT01_table-Final, KE25MOL-LBHT-IT..."
2,geno,11,"KE25MOL-EA21-AT01_table-Final, KE25MOL-LBHT-IT..."
3,plot,11,"KE25MOL-EA21-AT01_table-Final, KE25MOL-LBHT-IT..."
4,entry,11,"KE25MOL-EA21-AT01_table-Final, KE25MOL-LBHT-IT..."
...,...,...,...
127,Photo.1,1,KE25NJO-EA21-AT01_table-Final
128,Notes.1,1,KE25NJO-EA21-AT01_table-Final
129,Selected Clone,1,KE25MOL-EA21-AT01_table-Final
130,Weight In Air (Kgs),1,KE25NJO-EA21-AT01_table-Final
131,Weight In Water (Kgs),1,KE25NJO-EA21-AT01_table-Final

## Standardizing column names

In [26]:
#==========================================================
# CELL 13
# Standardize column names
#==========================================================

import re

def clean_names(df):

    df = df.copy()

    df.columns = (
        df.columns
          .str.strip()
          .str.lower()
          .str.replace(r"[^\w]+", "_", regex=True)
          .str.replace(r"_+", "_", regex=True)
          .str.strip("_")
    )

    return df

## Cleaning every sheet

In [27]:
#==========================================================
# CELL 14
# Clean every worksheet
#==========================================================

clean_trials = {}

for trial_name, sheets_dict in datasets.items():

    clean_trials[trial_name] = {}

    for sheet_name, df in sheets_dict.items():

        # Skip empty worksheets
        if df.empty:
            continue

        df = clean_names(df)

        # Remove empty rows
        df = df.dropna(how="all")

        # Remove empty columns
        df = df.dropna(axis=1, how="all")

        clean_trials[trial_name][sheet_name] = df

print("Cleaning complete.")

Cleaning complete.

### Validating the cleaning

In [28]:
#==========================================================
# CELL 15
# Summary of cleaned datasets
#==========================================================

summary = []

for trial_name, sheets_dict in clean_trials.items():

    for sheet_name, df in sheets_dict.items():

        summary.append({
            "Trial": trial_name,
            "Sheet": sheet_name,
            "Rows": df.shape[0],
            "Columns": df.shape[1],
            "Missing cells": int(df.isna().sum().sum())
        })

summary_df = pd.DataFrame(summary)

summary_df

                            Trial      Sheet  Rows  Columns  Missing cells
0   KE25MOL-EA21-AT01_table-Final  phenotype   174       27            107
1   KE25MOL-EA21-AT01_table-Final      yield   174       78            667
2   KE25MOL-LBHT-IT01_table-Final  phenotype   264       25            324
3   KE25MOL-LBHT-IT01_table-Final      yield   264       78           1256
4   KE25NJO-EA21-AT01_table-Final  phenotype   174       33            717
5   KE25NJO-LBHT-IT01_table-Final  phenotype   264       26            848
6   KE25NJO-LBHT-IT01_table-Final      yield   264       78            601
7   KE25UON-EA21-AT01_table-Final  phenotype   180       31            550
8   KE25UON-EA21-AT01_table-Final      yield   180       78            669
9   KE25UON-LBHT-IT01_table-Final  phenotype   264       30            808
10  KE25UON-LBHT-IT01_table-Final      yield   264       78            723

Now i want to make sure that phenotype and yield sheets can actually be merged safely. Remember: every phenotype observation should match exactly one yield observation (using: plot, geno, entry, row, column, rep)

If this is not true, the merge will duplicate records or lose observations

Checking merge keys

In [29]:
#==========================================================
# CELL 16
# Verify merge keys
#==========================================================

merge_keys = [
    "plot",
    "geno",
    "entry",
    "row",
    "column",
    "rep"
]

for trial_name, sheets_dict in clean_trials.items():

    if len(sheets_dict) != 2:
        continue

    sheet_names = list(sheets_dict.keys())

    pheno = sheets_dict[sheet_names[0]]
    yield_df = sheets_dict[sheet_names[1]]

    print("="*70)
    print(trial_name)

    print("Phenotype duplicates:",
          pheno.duplicated(subset=merge_keys).sum())

    print("Yield duplicates:",
          yield_df.duplicated(subset=merge_keys).sum())

======================================================================
KE25MOL-EA21-AT01_table-Final
Phenotype duplicates: 0
Yield duplicates: 0
======================================================================
KE25MOL-LBHT-IT01_table-Final
Phenotype duplicates: 0
Yield duplicates: 0
======================================================================
KE25NJO-LBHT-IT01_table-Final
Phenotype duplicates: 0
Yield duplicates: 0
======================================================================
KE25UON-EA21-AT01_table-Final
Phenotype duplicates: 0
Yield duplicates: 0
======================================================================
KE25UON-LBHT-IT01_table-Final
Phenotype duplicates: 0
Yield duplicates: 0

## Function to identify phenotype and yield sheets
instead of asuming the first sheet is phenotype, let's detect them automatically

In [30]:
#==========================================================
# CELL 17
# Identify phenotype and yield sheets
#==========================================================

def identify_sheets(sheet_dict):

    phenotype = None
    yield_sheet = None

    for name in sheet_dict.keys():

        if "yield" in name.lower():

            yield_sheet = name

        else:

            phenotype = name

    return phenotype, yield_sheet

## Merging the datasets

In [31]:
#==========================================================
# CELL 18
# Merge phenotype and yield
#==========================================================

merge_keys = [
    "plot",
    "geno",
    "entry",
    "row",
    "column",
    "rep"
]

merged_trials = {}

for trial_name, sheets_dict in clean_trials.items():

    pheno_sheet_name, yield_sheet_name = identify_sheets(sheets_dict)

    pheno_df = None
    yield_df = None

    if pheno_sheet_name:
        pheno_df = sheets_dict[pheno_sheet_name]
    if yield_sheet_name:
        yield_df = sheets_dict[yield_sheet_name]

    # Handle various combinations of sheet presence
    if pheno_df is None and yield_df is None:
        print(f"{trial_name} --> No phenotype or yield sheets found. Skipping.")
        continue
    elif pheno_df is None: # Only yield data available
        merged_trials[trial_name] = yield_df.copy()
        print(f"{trial_name} --> yield only")
        continue
    elif yield_df is None: # Only phenotype data available
        merged_trials[trial_name] = pheno_df.copy()
        print(f"{trial_name} --> phenotype only")
        continue
    else: # Both phenotype and yield data available, perform merge
        merged = pheno_df.merge(
            yield_df,
            on=merge_keys,
            how="left",
            suffixes=("", "_yield")
        )

        merged_trials[trial_name] = merged

        print(
            f"{trial_name}: "
            f"{pheno_df.shape[0]} -> {merged.shape[0]} rows"
        )

KE25MOL-EA21-AT01_table-Final: 174 -> 174 rows
KE25MOL-LBHT-IT01_table-Final: 264 -> 264 rows
KE25NJO-EA21-AT01_table-Final --> phenotype only
KE25NJO-LBHT-IT01_table-Final: 264 -> 264 rows
KE25UON-EA21-AT01_table-Final: 180 -> 180 rows
KE25UON-LBHT-IT01_table-Final: 264 -> 264 rows

## Creating a standard naming dictionary

In [32]:
rename_dict = {

    # Experimental design
    "plot":"plot",
    "geno":"geno",
    "entry":"entry",
    "row":"row",
    "column":"column",
    "rep":"rep",

    # Agronomic traits
    "growth_speed":"growth_speed",
    "pgh":"plant_height",
    "plant_unif":"plant_uniformity",
    "plant_vigor":"plant_vigor",
    "flowering":"flowering",
    "flowering_date":"flowering_date",
    "flower_colour":"flower_colour",
    "overall_impression":"overall_impression",

    "npe":"npe",
    "ntp":"ntp",
    "nph":"nph",

    "tuber_apper":"tuber_appearance",
    "tub_unif":"tuber_uniformity",
    "tub_size":"tuber_size",
    "skin_colour":"skin_colour",
    "flesh_colour":"flesh_colour",

    # Harvest traits
    "nmtcii":"nmtcii",
    "nmtci":"nmtci",
    "nnomtp":"nnomtp",
    "mtwci":"mtwci",
    "mtwcii":"mtwcii",
    "nomtwp":"nomtwp",

    # Dry matter
    "total_weight_in_kgs":"total_weight_kg",
    "weight_in_air_kgs":"weight_air_kg",
    "weight_in_water_kgs":"weight_water_kg",
    "dm":"dry_matter",

    # Disease
    "late_blight_30_days":"lb30",
    "late_blight_40_days":"lb40",
    "late_blight_50_days":"lb50",
    "late_blight_60_days":"lb60",
    "late_blight_70_days":"lb70",
    "late_blight_80_days":"lb80",
    "late_blight_90_days":"lb90",
    "late_blight_at_120_days":"lb120",

    # Stem counts
    "se":"se",
    "se_120_days":"se120",
    "se_100_days":"se100",
    "se_110_days":"se110",

    # Other
    "selected_clone":"selected",
    "selected_clones":"selected",
    "selected":"selected",
    "selected_and_non_selected":"selected",

    "greening_scale":"greening",
    "rotten_tubers":"rotten_tubers",
    "wilted":"wilted",
    "tubers_shape":"tuber_shape",

    "notes":"notes",
    "photo":"photo"
}

## Applying the standard names

In [33]:
for trial in clean_trials:

    for sheet in clean_trials[trial]:

        df = clean_trials[trial][sheet]

        df = df.rename(columns=rename_dict)

        clean_trials[trial][sheet] = df

print("Column names standardized.")

Column names standardized.

## CHecking remaining unmatched variables

In [34]:
all_variables = set()

for trial in clean_trials:

    for sheet in clean_trials[trial]:

        all_variables.update(clean_trials[trial][sheet].columns)

sorted(all_variables)

['0_10',
 '10_30',
 '30_35',
 '35_40',
 '40_45',
 '45_50',
 '50_55',
 '55_60',
 '60_65',
 '65_70',
 '70',
 'average_length_mm_0_10',
 'average_length_mm_10',
 'average_length_mm_10_30',
 'average_length_mm_30',
 'average_length_mm_30_35',
 'average_length_mm_35',
 'average_length_mm_35_40',
 'average_length_mm_40',
 'average_length_mm_40_45',
 'average_length_mm_45',
 'average_length_mm_45_50',
 'average_length_mm_50',
 'average_length_mm_50_55',
 'average_length_mm_55',
 'average_length_mm_55_60',
 'average_length_mm_60',
 'average_length_mm_60_65',
 'average_length_mm_65',
 'average_length_mm_65_70',
 'average_length_mm_70',
 'average_length_mm_total',
 'average_nir_value_total',
 'column',
 'comment',
 'dry_matter',
 'entry',
 'flesh_colour',
 'flower_colour',
 'flowering',
 'flowering_date',
 'geno',
 'growth_speed',
 'lb50',
 'lb60',
 'lb70',
 'lb80',
 'lb90',
 'name',
 'notes',
 'notes2',
 'notes_1',
 'npe',
 'nph',
 'ntp',
 'overall_impression',
 'owg_g_5kg_total',
 'owg_g_total',
 'photo',
 'photo_1',
 'plant_height',
 'plant_uniformity',
 'plant_vigor',
 'plot',
 'rep',
 'rotten_tubers',
 'row',
 'se',
 'selected',
 'skin_colour',
 'total',
 'total_weight_kg',
 'tuber_appearance',
 'tuber_shape',
 'tuber_size',
 'tuber_uniformity',
 'weight_0_10',
 'weight_10_30',
 'weight_30_35',
 'weight_35_40',
 'weight_40_45',
 'weight_45_50',
 'weight_50_55',
 'weight_55_60',
 'weight_60_65',
 'weight_65_70',
 'weight_70',
 'weight_air_kg',
 'weight_g_0_10',
 'weight_g_10_30',
 'weight_g_30_35',
 'weight_g_35_40',
 'weight_g_40_45',
 'weight_g_45_50',
 'weight_g_50_55',
 'weight_g_55_60',
 'weight_g_60_65',
 'weight_g_65_70',
 'weight_g_70',
 'weight_g_total',
 'weight_water_kg',
 'wilted']

## Identifying numeric columns

Some variables that should be numeric are currently stored as text because of empty cells or data entry inconsistencies.

In [35]:
for trial in clean_trials:

    print("\n", "="*60)
    print(trial)

    for sheet in clean_trials[trial]:

        print("\n", sheet)

        print(clean_trials[trial][sheet].dtypes.value_counts())

 ============================================================
KE25MOL-EA21-AT01_table-Final

 phenotype
int64             15
object             8
float64            3
datetime64[ns]     1
Name: count, dtype: int64

 yield
float64    71
int64       5
object      2
Name: count, dtype: int64

 ============================================================
KE25MOL-LBHT-IT01_table-Final

 phenotype
int64             15
object             6
float64            3
datetime64[ns]     1
Name: count, dtype: int64

 yield
float64    70
int64       6
object      2
Name: count, dtype: int64

 ============================================================
KE25NJO-EA21-AT01_table-Final

 phenotype
float64    14
int64      10
object      9
Name: count, dtype: int64

 ============================================================
KE25NJO-LBHT-IT01_table-Final

 phenotype
float64           10
int64              9
object             6
datetime64[ns]     1
Name: count, dtype: int64

 yield
float64    70
int64       6
object      2
Name: count, dtype: int64

 ============================================================
KE25UON-EA21-AT01_table-Final

 phenotype
int64             11
float64           10
object             9
datetime64[ns]     1
Name: count, dtype: int64

 yield
float64    70
int64       6
object      2
Name: count, dtype: int64

 ============================================================
KE25UON-LBHT-IT01_table-Final

 phenotype
float64           15
object             8
int64              6
datetime64[ns]     1
Name: count, dtype: int64

 yield
float64    56
int64      20
object      2
Name: count, dtype: int64

## Automatically converting numeric variables

In [36]:
for trial in clean_trials:

    for sheet in clean_trials[trial]:

        df = clean_trials[trial][sheet]

        # Iterate using positional index to handle duplicate column names
        for i, col_name in enumerate(df.columns):
            # Access the specific column by its positional index
            col_series = df.iloc[:, i]

            # Check the dtype of this specific column (which is a Series)
            if col_series.dtype == object:

                converted = pd.to_numeric(col_series, errors="coerce")

                # Convert only if at least 70% of non-missing values are numeric
                non_missing = col_series.notna().sum()

                if non_missing > 0:
                    if converted.notna().sum() / non_missing >= 0.70:
                        df.iloc[:, i] = converted  # Assign back by positional index

        clean_trials[trial][sheet] = df

print("✅ Numeric conversion completed.")

✅ Numeric conversion completed.

In [37]:
for trial in clean_trials:
    for sheet in clean_trials[trial]:

        df = clean_trials[trial][sheet]

        dup = df.columns[df.columns.duplicated()]

        if len(dup):

            print("="*60)
            print(trial)
            print(sheet)
            print(list(dup))

============================================================
KE25MOL-EA21-AT01_table-Final
yield
['0_10', '10_30', '30_35', '35_40', '40_45', '45_50', '50_55', '55_60', '60_65', '65_70', '70']
============================================================
KE25MOL-LBHT-IT01_table-Final
yield
['0_10', '10_30', '30_35', '35_40', '40_45', '45_50', '50_55', '55_60', '60_65', '65_70', '70']
============================================================
KE25NJO-LBHT-IT01_table-Final
yield
['0_10', '10_30', '30_35', '35_40', '40_45', '45_50', '50_55', '55_60', '60_65', '65_70', '70']
============================================================
KE25UON-EA21-AT01_table-Final
yield
['0_10', '10_30', '30_35', '35_40', '40_45', '45_50', '50_55', '55_60', '60_65', '65_70', '70']
============================================================
KE25UON-LBHT-IT01_table-Final
phenotype
['selected']
============================================================
KE25UON-LBHT-IT01_table-Final
yield
['0_10', '10_30', '30_35', '35_40', '40_45', '45_50', '50_55', '55_60', '60_65', '65_70', '70']

In [38]:
for trial in clean_trials:
    for sheet in clean_trials[trial]:

        df = clean_trials[trial][sheet]

        if len(df.columns) != len(set(df.columns)):
            print(trial, sheet)

KE25MOL-EA21-AT01_table-Final yield
KE25MOL-LBHT-IT01_table-Final yield
KE25NJO-LBHT-IT01_table-Final yield
KE25UON-EA21-AT01_table-Final yield
KE25UON-LBHT-IT01_table-Final phenotype
KE25UON-LBHT-IT01_table-Final yield

## Add trial information

In [39]:
master = []

# Helper function to ensure unique column names for a DataFrame
def make_columns_unique(df):
    cols = df.columns
    seen_counts = {}
    new_cols = []
    for col in cols:
        if col in seen_counts:
            seen_counts[col] += 1
            new_cols.append(f"{col}_{seen_counts[col]}")
        else:
            seen_counts[col] = 0 # First occurrence, count is 0 for no suffix
            new_cols.append(col)
    df.columns = new_cols
    return df

for trial_name, trial_df in merged_trials.items():
    # Make a copy to avoid modifying the original DataFrame in merged_trials
    current_df = trial_df.copy()

    # Ensure column names are unique within this DataFrame
    current_df = make_columns_unique(current_df)

    current_df["trial"] = trial_name

    location_prefix = trial_name.split("-")[0]

    if "MOL" in location_prefix:
        current_df["location"] = "Molo"
    elif "NJO" in location_prefix:
        current_df["location"] = "Njoro"
    elif "UON" in location_prefix:
        current_df["location"] = "Nairobi"

    # Extract population (e.g., EA21 from KE25MOL-EA21-AT01_table-Final)
    genotype_set = trial_name.split("-")[1]
    current_df["population"] = genotype_set

    master.append(current_df)

master_df = pd.concat(master, ignore_index=True)

print(master_df.shape)

(1320, 119)

In [40]:
master_df.head()

,plot,geno,entry,row,column,rep,ntp,npe,growth_speed,pgh,...,wilted,rotten_tubers,selected_and_non_selected,nph,late_blight_70_days,late_blight_80_days,photo,selected,tubers_shape,selected_clones
0,KE25MOL-EA21-AT01-00001,CIP3217004.022,10,1,1,1,20.0,20,5.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,KE25MOL-EA21-AT01-00002,CIP3177023.046,3,2,1,1,20.0,7,3.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,KE25MOL-EA21-AT01-00003,CIP3217016.038,47,3,1,1,20.0,15,5.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,KE25MOL-EA21-AT01-00004,CIP3217016.076,48,4,1,1,20.0,17,5.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,KE25MOL-EA21-AT01-00005,CIP3217006.008,20,5,1,1,20.0,16,7.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
master_df.columns

Index(['plot', 'geno', 'entry', 'row', 'column', 'rep', 'ntp', 'npe',
       'growth_speed', 'pgh',
       ...
       'wilted', 'rotten_tubers', 'selected_and_non_selected', 'nph',
       'late_blight_70_days', 'late_blight_80_days', 'photo', 'selected',
       'tubers_shape', 'selected_clones'],
      dtype='object', length=119)

## Saving Raw master dataset

In [42]:
(PROJECT / "data" / "processed").mkdir(parents=True, exist_ok=True)
master_df.to_csv(
    PROJECT / "data" / "processed" / "master_raw.csv",
    index=False
)

## Verifying trial sizes

In [43]:
master_df.groupby(
    ["location","population"]
).size()

location  population
Molo      EA21          174
          LBHT          264
Nairobi   EA21          180
          LBHT          264
Njoro     EA21          174
          LBHT          264
dtype: int64

## Looking for duplicate plots

In [44]:
master_df.duplicated(
    subset=["trial","plot"]
).sum()

np.int64(0)

## Checking replication

In [45]:
master_df.groupby(
    ["trial","rep"]
).size()

trial                          rep
KE25MOL-EA21-AT01_table-Final  1      174
KE25MOL-LBHT-IT01_table-Final  1      264
KE25NJO-EA21-AT01_table-Final  1      174
KE25NJO-LBHT-IT01_table-Final  1      264
KE25UON-EA21-AT01_table-Final  1      180
KE25UON-LBHT-IT01_table-Final  1      264
dtype: int64

# ==========================================================
# STAGE 3: QUALITY CONTROL (QC)
# ==========================================================

## Separate Numeric and Categorical Variables

In [46]:
# Numeric variables
numeric_cols = master_df.select_dtypes(include="number").columns.tolist()

# Character / categorical variables
categorical_cols = master_df.select_dtypes(exclude="number").columns.tolist()

print(f"Numeric variables: {len(numeric_cols)}")
print(f"Categorical variables: {len(categorical_cols)}")

Numeric variables: 101
Categorical variables: 18

In [47]:
print(numeric_cols[:20])
print(categorical_cols)

['entry', 'row', 'column', 'rep', 'ntp', 'npe', 'growth_speed', 'pgh', 'plant_unif', 'plant_vigor', 'flowering', 'overall_impression', 'se', 'tuber_apper', 'tub_unif', 'tub_size', 'late_blight_60_days', 'late_blight_90_days', 'name', 'comment']
['plot', 'geno', 'flowering_date', 'flower_colour', 'skin_colour', 'flesh_colour', 'notes', 'notes2', 'selected_clone', 'trial', 'location', 'population', 'notes_1', 'photo_1', 'photo', 'selected', 'tubers_shape', 'selected_clones']

## Checking variable types

In [48]:
dtype_table = (
    master_df
    .dtypes
    .reset_index()
)

dtype_table.columns = ["Variable", "Type"]

dtype_table

                Variable     Type
0                   plot   object
1                   geno   object
2                  entry    int64
3                    row    int64
4                 column    int64
..                   ...      ...
114  late_blight_80_days  float64
115                photo   object
116             selected   object
117         tubers_shape   object
118      selected_clones   object

[119 rows x 2 columns]

In [49]:
dtype_table.to_csv(
    PROJECT / "outputs" / "variable_types.csv",
    index=False
)

## Missing data summary

In [50]:
missing_summary = (
    master_df
    .isna()
    .mean()
    .mul(100)
    .round(2)
    .sort_values(ascending=False)
    .reset_index()
)

missing_summary.columns = [
    "Variable",
    "Percent Missing"
]

missing_summary.head(30)

                     Variable  Percent Missing
0             selected_clones            99.92
1                     photo_1            99.17
2                     notes_1            97.65
3                       photo            97.42
4                tubers_shape            96.74
5      average_length_mm_0_10            96.67
6   selected_and_non_selected            95.45
7               rotten_tubers            92.95
8         late_blight_70_days            92.88
9         late_blight_50_days            91.67
10                         dm            86.97
11             selected_clone            86.89
12        weight_in_water_kgs            86.82
13        total_weight_in_kgs            86.82
14          weight_in_air_kgs            86.82
15                     notes2            86.82
16                     wilted            77.80
17                        nph            72.12
18        late_blight_80_days            67.20
19                   selected            66.82
20       average_length_mm_70            55.68
21        late_blight_60_days            47.05
22    average_length_mm_65_70            45.45
23       average_length_mm_65            40.98
24    average_length_mm_60_65            32.20
25       average_length_mm_60            28.56
26              flower_colour            25.23
27    average_length_mm_55_60            25.00
28             flowering_date            23.79
29       average_length_mm_55            21.97

saving it

In [51]:
missing_summary.to_csv(
    PROJECT / "outputs" / "missing_summary.csv",
    index=False
)

## Variables completely missing

In [52]:
missing_summary[
    missing_summary["Percent Missing"] == 100
]

Empty DataFrame
Columns: [Variable, Percent Missing]
Index: []

In [53]:
missing_summary.head(20)

                     Variable  Percent Missing
0             selected_clones            99.92
1                     photo_1            99.17
2                     notes_1            97.65
3                       photo            97.42
4                tubers_shape            96.74
5      average_length_mm_0_10            96.67
6   selected_and_non_selected            95.45
7               rotten_tubers            92.95
8         late_blight_70_days            92.88
9         late_blight_50_days            91.67
10                         dm            86.97
11             selected_clone            86.89
12        weight_in_water_kgs            86.82
13        total_weight_in_kgs            86.82
14          weight_in_air_kgs            86.82
15                     notes2            86.82
16                     wilted            77.80
17                        nph            72.12
18        late_blight_80_days            67.20
19                   selected            66.82

In [54]:
missing_summary.tail(20)

               Variable  Percent Missing
99   overall_impression             0.61
100                  se             0.53
101                 pgh             0.53
102            tub_size             0.45
103         skin_colour             0.45
104        flesh_colour             0.45
105           flowering             0.30
106          plant_unif             0.23
107         plant_vigor             0.23
108        growth_speed             0.15
109                 npe             0.00
110                geno             0.00
111                plot             0.00
112              column             0.00
113                 rep             0.00
114               entry             0.00
115                 row             0.00
116          population             0.00
117               trial             0.00
118            location             0.00

In [55]:
high_missing = missing_summary[
    missing_summary["Percent Missing"] >= 95
]

high_missing

                    Variable  Percent Missing
0            selected_clones            99.92
1                    photo_1            99.17
2                    notes_1            97.65
3                      photo            97.42
4               tubers_shape            96.74
5     average_length_mm_0_10            96.67
6  selected_and_non_selected            95.45

using this rule:
<50% missing → keep
50–90% missing → inspect
>90% missing → candidate for removal

**Group 1: Essential variables (keep)**

These are the variables that will be used in the analyses.

Examples

plot
geno
rep
row
column
NTP
NPE
Growth_speed
PGH
Plant_vigor
Late Blight scores
Yield
Total weight
etc.

**Group 2: Administrative variables (remove)**

Examples

photo
photo_1
notes
notes_1
comment
name

These are not phenotypic traits.

***Group 3: Variables almost completely empty (remove)**

These include

selected_and_non_selected
selected_clone
tubers_shape
greening_scale
average_length_mm_0_10
etc.

unless they become useful later.

In [56]:
print(high_missing.keys())

Index(['Variable', 'Percent Missing'], dtype='object')

In [57]:
# Variables with >90% missing values

high_missing = {}

for trial, sheets in clean_trials.items():

    for sheet, df in sheets.items():

        miss = df.isna().mean() * 100

        bad = miss[miss > 90].sort_values(ascending=False)

        if len(bad):

            high_missing[(trial, sheet)] = bad

for (trial, sheet), bad in high_missing.items():

    print("="*70)
    print(trial)
    print(sheet)
    print(bad.index.tolist())

======================================================================
KE25MOL-LBHT-IT01_table-Final
yield
['average_length_mm_0_10']
======================================================================
KE25NJO-EA21-AT01_table-Final
phenotype
['photo_1']
======================================================================
KE25NJO-LBHT-IT01_table-Final
phenotype
['wilted', 'lb90']
======================================================================
KE25NJO-LBHT-IT01_table-Final
yield
['average_length_mm_0_10']
======================================================================
KE25UON-EA21-AT01_table-Final
phenotype
['lb70']
======================================================================
KE25UON-EA21-AT01_table-Final
yield
['average_length_mm_0_10']
======================================================================
KE25UON-LBHT-IT01_table-Final
phenotype
['selected']
======================================================================
KE25UON-LBHT-IT01_table-Final
yield
['average_length_mm_0_10']

Let's interpret each one.

Trial	Variable	Recommendation

KE25MOL-LBHT yield	average_length_mm_0_10	Remove

KE25NJO-EA21 phenotype	photo_1	Remove

KE25NJO-LBHT phenotype	wilted	Probably remove

KE25NJO-LBHT phenotype	lb90	Investigate first

KE25NJO-LBHT yield	average_length_mm_0_10	Remove

KE25UON-EA21 phenotype	lb70	Investigate first

KE25UON-EA21 yield	average_length_mm_0_10	Remove

KE25UON-LBHT yield	average_length_mm_0_10	Remove

In [58]:
for trial, sheets in clean_trials.items():

    for sheet, df in sheets.items():

        if "wilted" in df.columns:

            print("="*60)
            print(trial)
            print(df["wilted"].value_counts(dropna=False))

============================================================
KE25NJO-EA21-AT01_table-Final
wilted
NaN     71
1.0     20
2.0     19
3.0     14
4.0     11
5.0     10
6.0      6
8.0      6
10.0     5
7.0      3
12.0     3
15.0     3
11.0     2
16.0     1
Name: count, dtype: int64
============================================================
KE25NJO-LBHT-IT01_table-Final
wilted
NaN    257
1.0      4
2.0      2
3.0      1
Name: count, dtype: int64
============================================================
KE25UON-EA21-AT01_table-Final
wilted
NaN     27
1.0     23
2.0     21
3.0     18
6.0     13
7.0     12
9.0     11
4.0      8
5.0      6
11.0     6
15.0     6
10.0     6
14.0     4
8.0      4
12.0     4
0.0      3
13.0     3
18.0     2
16.0     2
19.0     1
Name: count, dtype: int64
============================================================
KE25UON-LBHT-IT01_table-Final
wilted
NaN    234
2.0     14
1.0      8
5.0      3
3.0      2
4.0      2
8.0      1
Name: count, dtype: int64

So far, we have

✅ Step 1: Read all Excel files

✅ Step 2: Identify phenotype and yield sheets

✅ Step 3: Remove empty sheets

✅ Step 4: Standardize column names

✅ Step 5: Remove empty rows and columns

✅ Step 6: Merge phenotype and yield

✅ Step 7: Initial missing-value QC

### Next i want to Harmonize variables across all trials

At the moment, different locations recorded the same trait with different names. (Late Blight 30 Days
late_blight_30_days
lb30)

## Creating a variable dictionary

In [59]:
# Trait harmonization dictionary

trait_dictionary = {

    # Experimental design
    "plot": "plot",
    "geno": "geno",
    "entry": "entry",
    "rep": "rep",
    "row": "row",
    "column": "column",

    # Emergence
    "ntp": "ntp",
    "npe": "npe",

    # Growth
    "growth_speed": "growth_speed",
    "pgh": "plant_height",
    "plant_unif": "plant_uniformity",
    "plant_vigor": "plant_vigor",

    # Flowering
    "flowering": "flowering",
    "flowering_date": "flowering_date",
    "flower_colour": "flower_colour",

    # Tuber traits
    "tuber_apper": "tuber_appearance",
    "tub_unif": "tuber_uniformity",
    "tub_size": "tuber_size",
    "skin_colour": "skin_colour",
    "flesh_colour": "flesh_colour",

    # Stem traits
    "se": "stem_number",

    # Plant traits
    "nph": "number_primary_haulms",

    # Yield components
    "nmtcii": "marketable_tubers_class2",
    "nmtci": "marketable_tubers_class1",
    "nnomtp": "non_marketable_tubers",
    "mtwci": "marketable_weight_class1",
    "mtwcii": "marketable_weight_class2",
    "nomtwp": "non_marketable_weight",

    # Disease
    "late_blight_30_days": "lb30",
    "late_blight_40_days": "lb40",
    "late_blight_50_days": "lb50",
    "late_blight_60_days": "lb60",
    "late_blight_70_days": "lb70",
    "late_blight_80_days": "lb80",
    "late_blight_90_days": "lb90",
    "late_blight_at_120_days": "lb120",

    # Dry matter
    "dm": "dry_matter",

    # Selection
    "selected": "selected"

}

## Renaming variables

In [60]:
for trial in clean_trials:

    for sheet in clean_trials[trial]:

        df = clean_trials[trial][sheet]

        df = df.rename(columns=trait_dictionary)

        clean_trials[trial][sheet] = df

print("Trait names standardized.")

Trait names standardized.

want to verify

In [61]:
for trial in clean_trials:

    print("="*70)
    print(trial)

    for sheet in clean_trials[trial]:

        print(sheet)

        cols = clean_trials[trial][sheet].columns.tolist()

        print(cols[:25])

======================================================================
KE25MOL-EA21-AT01_table-Final
phenotype
['plot', 'geno', 'entry', 'row', 'column', 'rep', 'ntp', 'npe', 'growth_speed', 'plant_height', 'plant_uniformity', 'plant_vigor', 'flowering', 'flowering_date', 'flower_colour', 'overall_impression', 'stem_number', 'tuber_appearance', 'tuber_uniformity', 'tuber_size', 'skin_colour', 'flesh_colour', 'lb60', 'lb90', 'notes']
yield
['plot', 'geno', 'entry', 'row', 'column', 'rep', 'name', 'comment', '0_10', '0_10', 'weight_g_0_10', 'weight_0_10', 'average_length_mm_0_10', '10_30', '10_30', 'weight_g_10_30', 'weight_10_30', 'average_length_mm_10_30', 'average_length_mm_10', '30_35', '30_35', 'weight_g_30_35', 'weight_30_35', 'average_length_mm_30_35', 'average_length_mm_30']
======================================================================
KE25MOL-LBHT-IT01_table-Final
phenotype
['plot', 'geno', 'entry', 'row', 'column', 'rep', 'ntp', 'npe', 'growth_speed', 'plant_height', 'plant_uniformity', 'plant_vigor', 'flowering', 'flowering_date', 'flower_colour', 'overall_impression', 'stem_number', 'tuber_appearance', 'skin_colour', 'tuber_size', 'tuber_uniformity', 'flesh_colour', 'lb60', 'lb90', 'notes']
yield
['plot', 'geno', 'entry', 'row', 'column', 'rep', 'name', 'comment', '0_10', '0_10', 'weight_g_0_10', 'weight_0_10', 'average_length_mm_0_10', '10_30', '10_30', 'weight_g_10_30', 'weight_10_30', 'average_length_mm_10_30', 'average_length_mm_10', '30_35', '30_35', 'weight_g_30_35', 'weight_30_35', 'average_length_mm_30_35', 'average_length_mm_30']
======================================================================
KE25NJO-EA21-AT01_table-Final
phenotype
['plot', 'geno', 'entry', 'row', 'column', 'rep', 'ntp', 'npe', 'growth_speed', 'plant_height', 'plant_uniformity', 'plant_vigor', 'flowering', 'flowering_date', 'flower_colour', 'overall_impression', 'stem_number', 'tuber_appearance', 'tuber_uniformity', 'tuber_size', 'flesh_colour', 'skin_colour', 'total_weight_kg', 'weight_air_kg', 'weight_water_kg']
======================================================================
KE25NJO-LBHT-IT01_table-Final
phenotype
['plot', 'geno', 'entry', 'row', 'column', 'rep', 'npe', 'growth_speed', 'plant_height', 'plant_uniformity', 'plant_vigor', 'flowering', 'flowering_date', 'flower_colour', 'overall_impression', 'stem_number', 'tuber_appearance', 'skin_colour', 'tuber_size', 'tuber_uniformity', 'flesh_colour', 'lb60', 'lb90', 'notes', 'wilted']
yield
['plot', 'geno', 'entry', 'row', 'column', 'rep', 'name', 'comment', '0_10', '0_10', 'weight_g_0_10', 'weight_0_10', 'average_length_mm_0_10', '10_30', '10_30', 'weight_g_10_30', 'weight_10_30', 'average_length_mm_10_30', 'average_length_mm_10', '30_35', '30_35', 'weight_g_30_35', 'weight_30_35', 'average_length_mm_30_35', 'average_length_mm_30']
======================================================================
KE25UON-EA21-AT01_table-Final
phenotype
['plot', 'geno', 'entry', 'row', 'column', 'rep', 'ntp', 'npe', 'growth_speed', 'plant_height', 'plant_uniformity', 'plant_vigor', 'flowering', 'flowering_date', 'flower_colour', 'overall_impression', 'stem_number', 'number_primary_haulms', 'tuber_appearance', 'tuber_uniformity', 'tuber_size', 'flesh_colour', 'skin_colour', 'lb70', 'lb80']
yield
['plot', 'geno', 'entry', 'row', 'column', 'rep', 'name', 'comment', '0_10', '0_10', 'weight_g_0_10', 'weight_0_10', 'average_length_mm_0_10', '10_30', '10_30', 'weight_g_10_30', 'weight_10_30', 'average_length_mm_10_30', 'average_length_mm_10', '30_35', '30_35', 'weight_g_30_35', 'weight_30_35', 'average_length_mm_30_35', 'average_length_mm_30']
======================================================================
KE25UON-LBHT-IT01_table-Final
phenotype
['plot', 'geno', 'entry', 'row', 'column', 'rep', 'ntp', 'npe', 'growth_speed', 'plant_height', 'plant_uniformity', 'plant_vigor', 'flowering', 'flowering_date', 'flower_colour', 'overall_impression', 'stem_number', 'number_primary_haulms', 'tuber_appearance', 'skin_colour', 'tuber_size', 'tuber_uniformity', 'flesh_colour', 'lb70', 'lb80']
yield
['plot', 'geno', 'entry', 'row', 'column', 'rep', 'name', 'comment', '0_10', '0_10', 'weight_g_0_10', 'weight_0_10', 'average_length_mm_0_10', '10_30', '10_30', 'weight_g_10_30', 'weight_10_30', 'average_length_mm_10_30', 'average_length_mm_10', '30_35', '30_35', 'weight_g_30_35', 'weight_30_35', 'average_length_mm_30_35', 'average_length_mm_30']

## Creating metadata

> Every observation should know:

where it came from,
which genotype set it belongs to,
which environment it belongs to.

Now adding that information.

In [62]:
for trial in clean_trials:

    if "MOL" in trial:
        location = "Molo"
    elif "NJO" in trial:
        location = "Njoro"
    elif "UON" in trial:
        location = "Nairobi"
    else:
        location = None

    if "EA21" in trial:
        population = "EA21"
    else:
        population = "LBHT"

    for sheet in clean_trials[trial]:

        df = clean_trials[trial][sheet]

        df["location"] = location
        df["population"] = population
        df["trial"] = trial

        clean_trials[trial][sheet] = df

print("Metadata added.")

Metadata added.

In [63]:
for trial in clean_trials:

    for sheet in clean_trials[trial]:

        df = clean_trials[trial][sheet]

        print(df[["trial","location","population"]].head())

                           trial location population
0  KE25MOL-EA21-AT01_table-Final     Molo       EA21
1  KE25MOL-EA21-AT01_table-Final     Molo       EA21
2  KE25MOL-EA21-AT01_table-Final     Molo       EA21
3  KE25MOL-EA21-AT01_table-Final     Molo       EA21
4  KE25MOL-EA21-AT01_table-Final     Molo       EA21
                           trial location population
0  KE25MOL-EA21-AT01_table-Final     Molo       EA21
1  KE25MOL-EA21-AT01_table-Final     Molo       EA21
2  KE25MOL-EA21-AT01_table-Final     Molo       EA21
3  KE25MOL-EA21-AT01_table-Final     Molo       EA21
4  KE25MOL-EA21-AT01_table-Final     Molo       EA21
                           trial location population
0  KE25MOL-LBHT-IT01_table-Final     Molo       LBHT
1  KE25MOL-LBHT-IT01_table-Final     Molo       LBHT
2  KE25MOL-LBHT-IT01_table-Final     Molo       LBHT
3  KE25MOL-LBHT-IT01_table-Final     Molo       LBHT
4  KE25MOL-LBHT-IT01_table-Final     Molo       LBHT
                           trial location population
0  KE25MOL-LBHT-IT01_table-Final     Molo       LBHT
1  KE25MOL-LBHT-IT01_table-Final     Molo       LBHT
2  KE25MOL-LBHT-IT01_table-Final     Molo       LBHT
3  KE25MOL-LBHT-IT01_table-Final     Molo       LBHT
4  KE25MOL-LBHT-IT01_table-Final     Molo       LBHT
                           trial location population
0  KE25NJO-EA21-AT01_table-Final    Njoro       EA21
1  KE25NJO-EA21-AT01_table-Final    Njoro       EA21
2  KE25NJO-EA21-AT01_table-Final    Njoro       EA21
3  KE25NJO-EA21-AT01_table-Final    Njoro       EA21
4  KE25NJO-EA21-AT01_table-Final    Njoro       EA21
                           trial location population
0  KE25NJO-LBHT-IT01_table-Final    Njoro       LBHT
1  KE25NJO-LBHT-IT01_table-Final    Njoro       LBHT
2  KE25NJO-LBHT-IT01_table-Final    Njoro       LBHT
3  KE25NJO-LBHT-IT01_table-Final    Njoro       LBHT
4  KE25NJO-LBHT-IT01_table-Final    Njoro       LBHT
                           trial location population
0  KE25NJO-LBHT-IT01_table-Final    Njoro       LBHT
1  KE25NJO-LBHT-IT01_table-Final    Njoro       LBHT
2  KE25NJO-LBHT-IT01_table-Final    Njoro       LBHT
3  KE25NJO-LBHT-IT01_table-Final    Njoro       LBHT
4  KE25NJO-LBHT-IT01_table-Final    Njoro       LBHT
                           trial location population
0  KE25UON-EA21-AT01_table-Final  Nairobi       EA21
1  KE25UON-EA21-AT01_table-Final  Nairobi       EA21
2  KE25UON-EA21-AT01_table-Final  Nairobi       EA21
3  KE25UON-EA21-AT01_table-Final  Nairobi       EA21
4  KE25UON-EA21-AT01_table-Final  Nairobi       EA21
                           trial location population
0  KE25UON-EA21-AT01_table-Final  Nairobi       EA21
1  KE25UON-EA21-AT01_table-Final  Nairobi       EA21
2  KE25UON-EA21-AT01_table-Final  Nairobi       EA21
3  KE25UON-EA21-AT01_table-Final  Nairobi       EA21
4  KE25UON-EA21-AT01_table-Final  Nairobi       EA21
                           trial location population
0  KE25UON-LBHT-IT01_table-Final  Nairobi       LBHT
1  KE25UON-LBHT-IT01_table-Final  Nairobi       LBHT
2  KE25UON-LBHT-IT01_table-Final  Nairobi       LBHT
3  KE25UON-LBHT-IT01_table-Final  Nairobi       LBHT
4  KE25UON-LBHT-IT01_table-Final  Nairobi       LBHT
                           trial location population
0  KE25UON-LBHT-IT01_table-Final  Nairobi       LBHT
1  KE25UON-LBHT-IT01_table-Final  Nairobi       LBHT
2  KE25UON-LBHT-IT01_table-Final  Nairobi       LBHT
3  KE25UON-LBHT-IT01_table-Final  Nairobi       LBHT
4  KE25UON-LBHT-IT01_table-Final  Nairobi       LBHT

# Data Harmonization
The data is clean but variables are not satandardized across locations

Listing all variables across all trials

In [64]:
all_variables = []

for trial, sheets in clean_trials.items():

    for sheet, df in sheets.items():

        for col in df.columns:

            all_variables.append({
                "Trial": trial,
                "Sheet": sheet,
                "Variable": col
            })

variables_df = pd.DataFrame(all_variables)

variables_df.head()

                           Trial      Sheet Variable
0  KE25MOL-EA21-AT01_table-Final  phenotype     plot
1  KE25MOL-EA21-AT01_table-Final  phenotype     geno
2  KE25MOL-EA21-AT01_table-Final  phenotype    entry
3  KE25MOL-EA21-AT01_table-Final  phenotype      row
4  KE25MOL-EA21-AT01_table-Final  phenotype   column

## Frequency of every variable

In [65]:
variable_summary = (
    variables_df
    .groupby("Variable")
    .size()
    .reset_index(name="Occurrences")
    .sort_values("Occurrences")
)

variable_summary

      Variable  Occurrences
51      notes2            1
52     notes_1            1
60     photo_1            1
59       photo            1
43        lb50            1
..         ...          ...
74       trial           11
64        plot           11
65  population           11
66         rep           11
68         row           11

[105 rows x 2 columns]

## To print uncommon variables

In [66]:
rare = variable_summary[
    variable_summary["Occurrences"] < 5
]

rare

                  Variable  Occurrences
51                  notes2            1
52                 notes_1            1
60                 photo_1            1
59                   photo            1
43                    lb50            1
35              dry_matter            1
73         total_weight_kg            1
67           rotten_tubers            1
90           weight_air_kg            1
76             tuber_shape            1
103        weight_water_kg            1
46                    lb80            2
55   number_primary_haulms            2
45                    lb70            2
44                    lb60            3
104                 wilted            4

## Renaming variables

In [67]:
rename_dict = {

    "lb30": "late_blight_30_days",
    "lb40": "late_blight_40_days",
    "lb50": "late_blight_50_days",
    "lb60": "late_blight_60_days",
    "lb70": "late_blight_70_days",
    "lb80": "late_blight_80_days",
    "lb90": "late_blight_90_days",

    "selected": "selected_clone",
    "selected_clones": "selected_clone",

    "photo_1": "photo",
    "notes_1": "notes",

    "se120_days": "se_120_days",
    "se_110_days": "se_110_days",
    "se_100_days": "se_100_days"

}

### applying the renaming

In [68]:
for trial, sheets in clean_trials.items():

    for sheet, df in sheets.items():

        clean_trials[trial][sheet] = df.rename(columns=rename_dict)

print("Variable harmonization complete.")

Variable harmonization complete.

## Saving another version

In [69]:
import os

harmonized_dir = PROJECT / "data" / "harmonized"

os.makedirs(harmonized_dir, exist_ok=True)

for trial, sheets in clean_trials.items():

    for sheet, df in sheets.items():

        outfile = harmonized_dir / f"{trial}_{sheet}.csv"

        df.to_csv(outfile, index=False)

print("Saved harmonized datasets.")

Saved harmonized datasets.

# PHASE 3 — Biological QC

A dataset can be perfectly clean but still contain biologically impossible values.

For example:

NTP = 50 plants (impossible)

Plant vigor = 9 when the scale is 1–5

Row = 30 when there are only 22 rows

Duplicate genotype names
Yield = -20 g

These won't be caught by simple cleaning.

## Creating a Trial summary

In [70]:
trial_summary = []

for trial, sheets in clean_trials.items():

    pheno = sheets.get("phenotype")
    yield_df = sheets.get("yield")

    trial_summary.append({

        "Trial": trial,

        "Phenotype rows":
            len(pheno) if pheno is not None else None,

        "Yield rows":
            len(yield_df) if yield_df is not None else None,

        "Genotypes":
            pheno["geno"].nunique()
            if pheno is not None else None,

        "Replicates":
            pheno["rep"].nunique()
            if pheno is not None else None,

        "Plots":
            pheno["plot"].nunique()
            if pheno is not None else None

    })

trial_summary = pd.DataFrame(trial_summary)

trial_summary

,Trial,Phenotype rows,Yield rows,Genotypes,Replicates,Plots
0,KE25MOL-EA21-AT01_table-Final,174,174.0,58,1,174
1,KE25MOL-LBHT-IT01_table-Final,264,264.0,118,1,264
2,KE25NJO-EA21-AT01_table-Final,174,NaN,58,1,174
3,KE25NJO-LBHT-IT01_table-Final,264,264.0,112,1,264
4,KE25UON-EA21-AT01_table-Final,180,180.0,59,1,180
5,KE25UON-LBHT-IT01_table-Final,264,264.0,120,1,264

## Checking genotype consistency

In [71]:
for trial, sheets in clean_trials.items():

    pheno = sheets.get("phenotype")

    if pheno is None:
        continue

    print("="*70)
    print(trial)

    print(sorted(pheno["geno"].dropna().unique())[:20])

    print("...")

    print("Total genotypes:",
          pheno["geno"].nunique())

======================================================================
KE25MOL-EA21-AT01_table-Final
['CIP312010.759', 'CIP312084.731', 'CIP3177023.046', 'CIP3177033.071', 'CIP3187015.677', 'CIP3187019.312', 'CIP3187028.088', 'CIP3217003.001', 'CIP3217003.020', 'CIP3217004.022', 'CIP3217004.036', 'CIP3217004.040', 'CIP3217004.058', 'CIP3217004.060', 'CIP3217004.089', 'CIP3217004.096', 'CIP3217004.132', 'CIP3217004.141', 'CIP3217005.093', 'CIP3217006.008']
...
Total genotypes: 58
======================================================================
KE25MOL-LBHT-IT01_table-Final
['CIP312079.001', 'CIP312079.002', 'CIP312079.003', 'CIP312079.004', 'CIP312079.006', 'CIP312079.008', 'CIP312079.009', 'CIP312079.010', 'CIP312079.011', 'CIP312079.012', 'CIP316348.047', 'CIP316348.096', 'CIP316349.006', 'CIP316349.017', 'CIP316349.030', 'CIP316349.031', 'CIP316349.032', 'CIP316349.040', 'CIP316349.066', 'CIP316349.070']
...
Total genotypes: 118
======================================================================
KE25NJO-EA21-AT01_table-Final
['CIP312010.759', 'CIP312084.731', 'CIP3177023.046', 'CIP3177033.071', 'CIP3187015.052', 'CIP3187015.677', 'CIP3187019.312', 'CIP3187028.088', 'CIP3217003.001', 'CIP3217004.022', 'CIP3217004.036', 'CIP3217004.040', 'CIP3217004.058', 'CIP3217004.060', 'CIP3217004.089', 'CIP3217004.096', 'CIP3217004.132', 'CIP3217005.093', 'CIP3217006.008', 'CIP3217006.021']
...
Total genotypes: 58
======================================================================
KE25NJO-LBHT-IT01_table-Final
['CIP312079.001', 'CIP312079.003', 'CIP312079.004', 'CIP312079.006', 'CIP312079.008', 'CIP312079.009', 'CIP312079.010', 'CIP312079.011', 'CIP316348.047', 'CIP316348.096', 'CIP316349.006', 'CIP316349.017', 'CIP316349.030', 'CIP316349.031', 'CIP316349.032', 'CIP316349.040', 'CIP316349.066', 'CIP316349.076', 'CIP316349.102', 'CIP316349.121']
...
Total genotypes: 112
======================================================================
KE25UON-EA21-AT01_table-Final
['CIP312010.759', 'CIP312084.731', 'CIP317007.008', 'CIP317026.032', 'CIP3177011.028', 'CIP3177033.071', 'CIP3177038.001', 'CIP3187015.677', 'CIP3187019.312', 'CIP3217003.001', 'CIP3217004.022', 'CIP3217004.036', 'CIP3217004.040', 'CIP3217004.058', 'CIP3217004.060', 'CIP3217004.089', 'CIP3217004.096', 'CIP3217004.132', 'CIP3217004.141', 'CIP3217005.093']
...
Total genotypes: 59
======================================================================
KE25UON-LBHT-IT01_table-Final
['CIP312079.001', 'CIP312079.002', 'CIP312079.006', 'CIP312079.008', 'CIP312079.009', 'CIP312079.010', 'CIP315360.117', 'CIP316348.047', 'CIP316348.096', 'CIP316349.006', 'CIP316349.017', 'CIP316349.030', 'CIP316349.031', 'CIP316349.032', 'CIP316349.040', 'CIP316349.066', 'CIP316349.070', 'CIP316349.076', 'CIP316349.102', 'CIP316349.121']
...
Total genotypes: 120

## comparing genotype lists across enironments

In [72]:
# Compare genotype lists among environments

ea21_sets = {}
lbht_sets = {}

for trial_name, df in merged_trials.items():

    # Ensure 'geno' column exists in the DataFrame
    if "geno" not in df.columns:
        print(f"Warning: 'geno' column not found in {trial_name}. Skipping.")
        continue

    genotypes = set(df["geno"].dropna())

    if "EA21" in trial_name:
        ea21_sets[trial_name] = genotypes

    if "LBHT" in trial_name:
        lbht_sets[trial_name] = genotypes

## Comparing EA21

In [73]:
from itertools import combinations

for a, b in combinations(ea21_sets.keys(), 2):

    print("="*70)
    print(a)
    print(b)

    print("\nOnly in first trial:")
    print(sorted(ea21_sets[a] - ea21_sets[b]))

    print("\nOnly in second trial:")
    print(sorted(ea21_sets[b] - ea21_sets[a]))

======================================================================
KE25MOL-EA21-AT01_table-Final
KE25NJO-EA21-AT01_table-Final

Only in first trial:
['CIP3217003.020', 'CIP3217004.141', 'CIP3217019.104']

Only in second trial:
['CIP3187015.052', 'CIP3217014.121', 'Wanjiku']
======================================================================
KE25MOL-EA21-AT01_table-Final
KE25UON-EA21-AT01_table-Final

Only in first trial:
['CIP3177023.046', 'CIP3187028.088', 'CIP3217003.020', 'CIP3217006.008', 'CIP3217016.033', 'CIP3217016.038', 'CIP3217017.254', 'CIP3217019.104']

Only in second trial:
['CIP317007.008', 'CIP317026.032', 'CIP3177011.028', 'CIP3177038.001', 'CIP3217014.121', 'NARI005', 'Wanjiku', 'dummy-Shangi', 'dummy-Sherekea']
======================================================================
KE25NJO-EA21-AT01_table-Final
KE25UON-EA21-AT01_table-Final

Only in first trial:
['CIP3177023.046', 'CIP3187015.052', 'CIP3187028.088', 'CIP3217006.008', 'CIP3217016.033', 'CIP3217016.038', 'CIP3217017.254']

Only in second trial:
['CIP317007.008', 'CIP317026.032', 'CIP3177011.028', 'CIP3177038.001', 'CIP3217004.141', 'NARI005', 'dummy-Shangi', 'dummy-Sherekea']

## Comparing LBHT

In [74]:
from itertools import combinations

def compare_genotypes(trial1_name, trial2_name, genotype_sets_dict):
    print("="*70)
    print(trial1_name)
    print(trial2_name)

    print("\nOnly in first trial:")
    print(sorted(genotype_sets_dict[trial1_name] - genotype_sets_dict[trial2_name]))

    print("\nOnly in second trial:")
    print(sorted(genotype_sets_dict[trial2_name] - genotype_sets_dict[trial1_name]))

ea21_trials = [
    "KE25MOL-EA21-AT01_table-Final",
    "KE25NJO-EA21-AT01_table-Final",
    "KE25UON-EA21-AT01_table-Final"
]

lbht_trials = [
    "KE25MOL-LBHT-IT01_table-Final",
    "KE25NJO-LBHT-IT01_table-Final",
    "KE25UON-LBHT-IT01_table-Final"
]

print("========== EA21 ==========")

for t1, t2 in combinations(ea21_trials, 2):
    compare_genotypes(t1, t2, ea21_sets)

print("\n========== LBHT ==========")

for t1, t2 in combinations(lbht_trials, 2):
    compare_genotypes(t1, t2, lbht_sets)

========== EA21 ==========
======================================================================
KE25MOL-EA21-AT01_table-Final
KE25NJO-EA21-AT01_table-Final

Only in first trial:
['CIP3217003.020', 'CIP3217004.141', 'CIP3217019.104']

Only in second trial:
['CIP3187015.052', 'CIP3217014.121', 'Wanjiku']
======================================================================
KE25MOL-EA21-AT01_table-Final
KE25UON-EA21-AT01_table-Final

Only in first trial:
['CIP3177023.046', 'CIP3187028.088', 'CIP3217003.020', 'CIP3217006.008', 'CIP3217016.033', 'CIP3217016.038', 'CIP3217017.254', 'CIP3217019.104']

Only in second trial:
['CIP317007.008', 'CIP317026.032', 'CIP3177011.028', 'CIP3177038.001', 'CIP3217014.121', 'NARI005', 'Wanjiku', 'dummy-Shangi', 'dummy-Sherekea']
======================================================================
KE25NJO-EA21-AT01_table-Final
KE25UON-EA21-AT01_table-Final

Only in first trial:
['CIP3177023.046', 'CIP3187015.052', 'CIP3187028.088', 'CIP3217006.008', 'CIP3217016.033', 'CIP3217016.038', 'CIP3217017.254']

Only in second trial:
['CIP317007.008', 'CIP317026.032', 'CIP3177011.028', 'CIP3177038.001', 'CIP3217004.141', 'NARI005', 'dummy-Shangi', 'dummy-Sherekea']

========== LBHT ==========
======================================================================
KE25MOL-LBHT-IT01_table-Final
KE25NJO-LBHT-IT01_table-Final

Only in first trial:
['CIP312079.002', 'CIP312079.012', 'CIP316349.070', 'CIP316357.070', 'CIP316361.108', 'CIP316363.033', 'CIP316363.069']

Only in second trial:
['CIP316358.069']
======================================================================
KE25MOL-LBHT-IT01_table-Final
KE25UON-LBHT-IT01_table-Final

Only in first trial:
['CIP312079.003', 'CIP312079.004', 'CIP312079.011', 'CIP312079.012', 'CIP316361.029', 'CIP316361.108', 'CIP316364.010', 'CIP316384.065']

Only in second trial:
['CIP315360.117', 'CIP316358.069', 'CIP316363.005', 'CIP316363.013', 'CIP3163643.092', 'CIP316365.078', 'CIP316367.036', 'CIP316367.097', 'CIP316367.098', 'Wanjiku']
======================================================================
KE25NJO-LBHT-IT01_table-Final
KE25UON-LBHT-IT01_table-Final

Only in first trial:
['CIP312079.003', 'CIP312079.004', 'CIP312079.011', 'CIP316361.029', 'CIP316364.010', 'CIP316384.065']

Only in second trial:
['CIP312079.002', 'CIP315360.117', 'CIP316349.070', 'CIP316357.070', 'CIP316363.005', 'CIP316363.013', 'CIP316363.033', 'CIP316363.069', 'CIP3163643.092', 'CIP316365.078', 'CIP316367.036', 'CIP316367.097', 'CIP316367.098', 'Wanjiku']

In [75]:
for trial in clean_trials.keys():
    print(trial)

KE25MOL-EA21-AT01_table-Final
KE25MOL-LBHT-IT01_table-Final
KE25NJO-EA21-AT01_table-Final
KE25NJO-LBHT-IT01_table-Final
KE25UON-EA21-AT01_table-Final
KE25UON-LBHT-IT01_table-Final

In [76]:
lbht_trials = [
    "KE25MOL-LBHT-IT01_table-Final",
    "KE25NJO-LBHT-IT01_table-Final",
    "KE25UON-LBHT-IT01_table-Final"
]

for trial in lbht_trials:
    # Using lbht_sets which was correctly populated from merged_trials
    # and contains genotypes for all relevant trials.
    print(trial,
          len(lbht_sets[trial]))

KE25MOL-LBHT-IT01_table-Final 118
KE25NJO-LBHT-IT01_table-Final 112
KE25UON-LBHT-IT01_table-Final 120

comparing all three pairwise

In [77]:
from itertools import combinations

for t1, t2 in combinations(lbht_trials, 2):

    # Use the pre-computed lbht_sets to get genotypes to avoid KeyError
    g1 = lbht_sets[t1]
    g2 = lbht_sets[t2]

    print("="*70)
    print(t1)
    print(t2)

    print("\nOnly in first:")
    print(sorted(g1 - g2))

    print("\nOnly in second:")
    print(sorted(g2 - g1))

======================================================================
KE25MOL-LBHT-IT01_table-Final
KE25NJO-LBHT-IT01_table-Final

Only in first:
['CIP312079.002', 'CIP312079.012', 'CIP316349.070', 'CIP316357.070', 'CIP316361.108', 'CIP316363.033', 'CIP316363.069']

Only in second:
['CIP316358.069']
======================================================================
KE25MOL-LBHT-IT01_table-Final
KE25UON-LBHT-IT01_table-Final

Only in first:
['CIP312079.003', 'CIP312079.004', 'CIP312079.011', 'CIP312079.012', 'CIP316361.029', 'CIP316361.108', 'CIP316364.010', 'CIP316384.065']

Only in second:
['CIP315360.117', 'CIP316358.069', 'CIP316363.005', 'CIP316363.013', 'CIP3163643.092', 'CIP316365.078', 'CIP316367.036', 'CIP316367.097', 'CIP316367.098', 'Wanjiku']
======================================================================
KE25NJO-LBHT-IT01_table-Final
KE25UON-LBHT-IT01_table-Final

Only in first:
['CIP312079.003', 'CIP312079.004', 'CIP312079.011', 'CIP316361.029', 'CIP316364.010', 'CIP316384.065']

Only in second:
['CIP312079.002', 'CIP315360.117', 'CIP316349.070', 'CIP316357.070', 'CIP316363.005', 'CIP316363.013', 'CIP316363.033', 'CIP316363.069', 'CIP3163643.092', 'CIP316365.078', 'CIP316367.036', 'CIP316367.097', 'CIP316367.098', 'Wanjiku']

My observations

1. Molo vs Njoro LBHT

Only 8 genotypes differ (7 unique to Molo and 1 unique to Njoro).

This is quite reasonable. It could be due to:

missing seed,
failed plots,
accidental omission,
or one replacement genotype.

This doesn't cause much worry.

2. Molo vs UON LBHT

This is more interesting.

UON has several genotypes that Molo doesn't:

CIP315360.117
CIP316363.005
CIP316363.013
CIP3163643.092
CIP316365.078
CIP316367.036
CIP316367.097
CIP316367.098
Wanjiku

while Molo has

CIP312079.003
CIP312079.004
CIP312079.011
CIP312079.012
CIP316361.029
CIP316361.108
CIP316364.010
CIP316384.065


- This genotype: CIP3163643.092 looks suspicious. Comparing it with CIP316364.010 ; notice the extra **3** after **316364**
it may be ** CIP316364.092** instead of **CIP3163643.092**

- Check varieties may appear twice

## Searching for suspicious genotype names

In [78]:
all_genotypes = set()

# Iterate through merged_trials instead of clean_trials to access all processed genotypes
for trial_name, df in merged_trials.items():
    # Ensure 'geno' column exists before trying to access it
    if "geno" in df.columns:
        all_genotypes.update(df["geno"].dropna().unique())

for g in sorted(all_genotypes):
    print(g)

CIP312010.759
CIP312079.001
CIP312079.002
CIP312079.003
CIP312079.004
CIP312079.006
CIP312079.008
CIP312079.009
CIP312079.010
CIP312079.011
CIP312079.012
CIP312084.731
CIP315360.117
CIP316348.047
CIP316348.096
CIP316349.006
CIP316349.017
CIP316349.030
CIP316349.031
CIP316349.032
CIP316349.040
CIP316349.066
CIP316349.070
CIP316349.076
CIP316349.102
CIP316349.121
CIP316349.128
CIP316349.134
CIP316349.140
CIP316349.141
CIP316352.008
CIP316352.027
CIP316352.076
CIP316353.015
CIP316353.019
CIP316353.026
CIP316353.030
CIP316353.035
CIP316353.048
CIP316353.054
CIP316353.058
CIP316353.059
CIP316353.104
CIP316353.128
CIP316353.129
CIP316354.164
CIP316354.165
CIP316355.037
CIP316355.041
CIP316356.023
CIP316357.016
CIP316357.059
CIP316357.067
CIP316357.070
CIP316358.029
CIP316358.055
CIP316358.069
CIP316358.070
CIP316358.138
CIP316359.004
CIP316359.026
CIP316359.036
CIP316359.061
CIP316359.117
CIP316359.151
CIP316360.018
CIP316360.145
CIP316361.010
CIP316361.022
CIP316361.025
CIP316361.029
CIP316361.030
CIP316361.035
CIP316361.037
CIP316361.045
CIP316361.069
CIP316361.078
CIP316361.085
CIP316361.094
CIP316361.108
CIP316361.135
CIP316362.019
CIP316363.005
CIP316363.010
CIP316363.013
CIP316363.028
CIP316363.029
CIP316363.033
CIP316363.048
CIP316363.055
CIP316363.056
CIP316363.058
CIP316363.065
CIP316363.069
CIP316363.081
CIP316363.092
CIP316363.094
CIP316363.095
CIP316363.096
CIP316363.103
CIP316364.010
CIP316364.012
CIP316364.033
CIP316364.034
CIP316364.043
CIP3163643.092
CIP316365.001
CIP316365.058
CIP316365.078
CIP316366.015
CIP316366.044
CIP316366.132
CIP316367.036
CIP316367.048
CIP316367.075
CIP316367.087
CIP316367.088
CIP316367.097
CIP316367.098
CIP316367.103
CIP316367.120
CIP316371.148
CIP316376.014
CIP316376.020
CIP316384.065
CIP317007.008
CIP317026.032
CIP3177011.028
CIP3177023.046
CIP3177033.071
CIP3177038.001
CIP3187015.052
CIP3187015.677
CIP3187019.312
CIP3187028.088
CIP3217003.001
CIP3217003.020
CIP3217004.022
CIP3217004.036
CIP3217004.040
CIP3217004.058
CIP3217004.060
CIP3217004.089
CIP3217004.096
CIP3217004.132
CIP3217004.141
CIP3217005.093
CIP3217006.008
CIP3217006.021
CIP3217006.028
CIP3217006.073
CIP3217006.103
CIP3217007.005
CIP3217008.024
CIP3217008.070
CIP3217008.098
CIP3217011.009
CIP3217012.120
CIP3217014.002
CIP3217014.004
CIP3217014.049
CIP3217014.058
CIP3217014.061
CIP3217014.111
CIP3217014.112
CIP3217014.121
CIP3217014.137
CIP3217014.143
CIP3217015.071
CIP3217015.123
CIP3217016.011
CIP3217016.020
CIP3217016.033
CIP3217016.034
CIP3217016.038
CIP3217016.076
CIP3217017.050
CIP3217017.254
CIP3217019.001
CIP3217019.004
CIP3217019.104
NARI002
NARI004
NARI005
Sagitta
Shangi
Sherekea
Unica
Wanjiku
dummy-Shangi
dummy-Sherekea

## Genotype frequencies

In [79]:
from collections import Counter

geno_counter = Counter()

# Iterate through merged_trials instead of clean_trials
for trial_name, df in merged_trials.items():
    # Check if 'geno' column exists in the DataFrame
    if "geno" in df.columns:
        geno_counter.update(df["geno"].dropna())

freq = (
    pd.DataFrame({
        "Genotype": list(geno_counter.keys()),
        "Occurrences": list(geno_counter.values())
    })
    .sort_values("Occurrences")
    .reset_index(drop=True)
)

freq.head(30)

          Genotype  Occurrences
0   CIP3217019.104            1
1   CIP3217003.020            1
2    CIP317007.008            1
3    CIP316367.097            1
4    CIP316363.005            1
5    CIP316365.078            1
6    CIP315360.117            1
7   CIP3163643.092            1
8    CIP317026.032            1
9   CIP3177011.028            1
10   CIP316367.036            1
11   CIP316361.108            1
12         NARI005            1
13   CIP316367.098            1
14   CIP312079.012            2
15  CIP3187015.052            2
16  CIP3177038.001            2
17   CIP316363.013            2
18   CIP312079.011            3
19   CIP312079.003            3
20   CIP312079.002            3
21   CIP316364.010            3
22  dummy-Sherekea            3
23    dummy-Shangi            3
24   CIP316384.065            3
25   CIP316349.070            3
26   CIP316363.069            3
27   CIP316349.030            4
28   CIP312079.004            4
29  CIP3217016.038            4

# **NOTES**

**1. We have confirmed that the trials are unbalanced**

If every genotype had been planted in every location:

EA21 genotypes should occur 3 times (Molo, Njoro, UON).
LBHT genotypes should also occur 3 times.

Instead, we see:

Occurrence = 1
Occurrence = 2
Occurrence = 3
Occurrence = 4

This immediately tells us the genotype lists differ among environments.

**2. Occurrence = 4 deserves investigation**

For example

CIP316349.030
CIP312079.004
CIP3217016.038

appear 4 times.

That cannot happen if they belong to only one trial planted in three locations.

This suggests one of these possibilities:

the genotype appears in both EA21 and LBHT (unlikely),
duplicate naming,
duplicate records,
or the genotype genuinely belongs to both populations.

We need to check.

In [80]:
for trial in clean_trials:
    if "phenotype" in clean_trials[trial]: # Add this check
        pheno = clean_trials[trial]["phenotype"]

        if "geno" in pheno.columns:

            if "CIP316349.030" in pheno["geno"].values:

                print(trial)

KE25MOL-LBHT-IT01_table-Final
KE25NJO-LBHT-IT01_table-Final
KE25UON-LBHT-IT01_table-Final

In [81]:
for trial in clean_trials:
    if "phenotype" in clean_trials[trial]: # Add this check
        pheno = clean_trials[trial]["phenotype"]

        if "geno" in pheno.columns:

            if pheno["geno"].astype(str).str.contains("316364").any():

                print("\n", trial)

                print(
                    pheno.loc[
                        pheno["geno"].astype(str).str.contains("316364"),
                        "geno"
                    ].unique()
                )

 KE25MOL-LBHT-IT01_table-Final
['CIP316364.033' 'CIP316364.043' 'CIP316364.012' 'CIP316364.034'
 'CIP316364.010']

 KE25NJO-LBHT-IT01_table-Final
['CIP316364.033' 'CIP316364.010' 'CIP316364.012' 'CIP316364.034'
 'CIP316364.043']

 KE25UON-LBHT-IT01_table-Final
['CIP316364.033' 'CIP316364.043' 'CIP316364.012' 'CIP316364.034'
 'CIP3163643.092']

### Confirming the UON phenotype exists

In [82]:
print(clean_trials["KE25UON-LBHT-IT01_table-Final"].keys())

dict_keys(['phenotype', 'yield'])

In [83]:
for trial, sheets in clean_trials.items():
    print("\n", trial)
    print(sheets.keys())

 KE25MOL-EA21-AT01_table-Final
dict_keys(['phenotype', 'yield'])

 KE25MOL-LBHT-IT01_table-Final
dict_keys(['phenotype', 'yield'])

 KE25NJO-EA21-AT01_table-Final
dict_keys(['phenotype'])

 KE25NJO-LBHT-IT01_table-Final
dict_keys(['phenotype', 'yield'])

 KE25UON-EA21-AT01_table-Final
dict_keys(['phenotype', 'yield'])

 KE25UON-LBHT-IT01_table-Final
dict_keys(['phenotype', 'yield'])

In [84]:
print(datasets["KE25UON-LBHT-IT01_table-Final"].keys())

dict_keys(['phenotype', 'yield'])

In [85]:
clean_trials["KE25UON-LBHT-IT01_table-Final"]["phenotype"] = (
    datasets["KE25UON-LBHT-IT01_table-Final"]["phenotype"]
    .copy()
)

print(clean_trials["KE25UON-LBHT-IT01_table-Final"].keys())

dict_keys(['phenotype', 'yield'])

In [86]:
clean_trials["KE25UON-LBHT-IT01_table-Final"]["phenotype"].shape

(264, 45)

Checking the original imported workbook

In [87]:
for sheet_name, df in datasets["KE25UON-LBHT-IT01_table-Final"].items():
    print("=" * 50)
    print(sheet_name)
    print(df.shape)

==================================================
phenotype
(264, 45)
==================================================
yield
(264, 80)

In Thi notebook I have done:

✔ imported all six Excel workbooks,

✔ identified phenotype and yield sheets,

✔ removed empty sheets (including the problematic UON sheet),

✔ harmonized column names using clean_names(),

✔ converted variables to appropriate data types,

✔ merged phenotype and yield within each trial,

✔ performed quality checks,

✔ examined missingness,

✔ checked duplicate rows,

✔ compared genotype lists across locations,

✔ saved the cleaned object (clean_trials.pkl

I will move to notebook 02 where i prepare the data for spatial and multi-environment analysis